### ISSUE TITLE
"Couldn't open file lang/english.txt!" error.

### ISSUE THREAD

**Issue by zenolth** [tilkinsc/LuaConsole#35]
I'm trying to run a *.lua file using LuaConsole on Windows by doing `luaw main.lua` but only thing I get every time is : 
`Couldn't open file lang/english.txt!
Failed to load lang file!`

**Comment by tilkinsc** [comment]
This is because lang/english.txt can't be found. It needs to be within the installation directory. Perhaps cwd.
You should use the development branch, as some oddities are repaired. 
`git clone --branch development https://github.com/tilkinsc/LuaConsole`

**Comment by tilkinsc** [comment]
[LuaConsole.zip](https://github.com/tilkinsc/LuaConsole/files/10202327/LuaConsole.zip)
Here is a prebuilt for windows. It should be directory independent now as long as lang/* is next to the folder. I included luajit as the primary, and lua-5.1.5, lua-5.2.4, lua-5.3.6, and lua-5.4.4
